apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-demo
  namespace: devops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-demo

  template:

    metadata:
      labels:
        app: devops-demo

    spec:

      containers:

      - name: devops-demo

        image: mobarez1/devops-demo:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 5000
